### PR TITLE
Feature/1226

### PR DESCRIPTION
**Pull request by medullaskyline**

### CODE REVIEW

**Comment by medullaskyline** [comment]
@phyllers I have to generate documentation and write some code examples before this gets released into prod, FYI.

**Comment by phyllers** [comment]
I've assigned @kleisb. 

I'd like to merge this and have it for this sprint. Also since we are discussing other code refactoring for metadata, it would be handy to have this in master. @medullaskyline do you think you will have the documentation and code examples ready for this sprint?

**Comment by medullaskyline** [comment]
You mean sprint 6, June 29? If so, then yes.

**Comment by phyllers** [comment]
Great! @kleisb if you want to merge this in while I'm away, I'm fine with that.

**Pull request merged**
